// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9pEYMZBNhoCeNma5LEM-M6fd_BQX6acE',
    appId: '1:532084031418:web:7ca0e7c4a112ce2027a783',
    messagingSenderId: '532084031418',
    projectId: 'quanlyquanantka',
    authDomain: 'quanlyquanantka.firebaseapp.com',
    storageBucket: 'quanlyquanantka.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHx1N55icCU2Hk9dgcivVWh7vG81xNUOI',
    appId: '1:532084031418:android:87e443d5e5fc6f6527a783',
    messagingSenderId: '532084031418',
    projectId: 'quanlyquanantka',
    storageBucket: 'quanlyquanantka.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcadLnCq_-0-VpSW_ZBLgVRm5yBGNMbYY',
    appId: '1:532084031418:ios:d4aa58b0e25b9ca627a783',
    messagingSenderId: '532084031418',
    projectId: 'quanlyquanantka',
    storageBucket: 'quanlyquanantka.firebasestorage.app',
    iosBundleId: 'com.example.doAnMonQuanlyquanan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcadLnCq_-0-VpSW_ZBLgVRm5yBGNMbYY',
    appId: '1:532084031418:ios:d4aa58b0e25b9ca627a783',
    messagingSenderId: '532084031418',
    projectId: 'quanlyquanantka',
    storageBucket: 'quanlyquanantka.firebasestorage.app',
    iosBundleId: 'com.example.doAnMonQuanlyquanan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9pEYMZBNhoCeNma5LEM-M6fd_BQX6acE',
    appId: '1:532084031418:web:79d4b6468d2e8d6427a783',
    messagingSenderId: '532084031418',
    projectId: 'quanlyquanantka',
    authDomain: 'quanlyquanantka.firebaseapp.com',
    storageBucket: 'quanlyquanantka.firebasestorage.app',
  );
}
